name: invmovieconcept1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.1.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependency_overrides:
  path: 1.8.0
  intl: 0.17.0
  xml: 5.3.0
  image: 3.0.2
  signature: 4.0.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  tuple: 2.0.0
  animate_do: 2.0.0
  supercharged: 2.1.1

  emojis: 0.9.3
  barcode: 2.1.0
  tinycolor: 1.0.3
  flutter_icons: 1.1.0
  dotted_border: 2.0.0+1
  barcode_widget: 2.0.1
  touchable_opacity: 1.2.0
  page_transition: 2.0.2
  simple_animations: 3.2.0
  cupertino_will_pop_scope: 1.2.0

  share: 2.0.4
  open_url: 2.0.0
  provider: 6.0.0
  url_launcher: 6.0.11
  universal_io: 2.0.4

  firebase_core: 1.11.0
  google_mobile_ads: 1.0.1
  firebase_analytics: 9.0.5
  firebase_performance: 0.8.0+4
  firebase_crashlytics:
    path: ./packages/firebase_crashlytics

  shared_preferences: 2.0.11

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  msix: 2.8.1
  io: 1.0.0
  yaml: 3.1.0
  glob: 2.0.1
  translator: 0.1.7

flutter_icons:
  includes:
    - mco

flutter:
  uses-material-design: true
  assets:
    - assets/langs/
    - assets/icons/
    - assets/movies/
    - assets/avatars/

  fonts:
    - family: Muli
      fonts:
        - asset: fonts/Muli/Muli-Light.ttf
          weight: 300
        - asset: fonts/Muli/Muli-Regular.ttf
          weight: 400
        - asset: fonts/Muli/Muli-SemiBold.ttf
          weight: 600
        - asset: fonts/Muli/Muli-Bold.ttf
          weight: 700

msix_config:
  store: true
  msix_version: 1.0.0.0
  publisher_display_name: OneMDev
  logo_path: ./assets/icons/app-icon.png
  display_name: Flutter Movie Concept UI
  identity_name: 39858OneMDev.FlutterMovieConceptUI
  publisher: CN=309E1851-D363-4893-8248-5E01652D9CF1
