on:
  push:
    tags:
      - '*'

name: Release Builds
jobs:
  android-aab:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
      - run: |
          flutter pub get
          dart ./scripts/splitVectorIcons.dart
          flutter build appbundle -t lib/main.mobile.dart
      - name: Create Android Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/bundle/release/app-release.aab'
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
      - name: Create service_account.json
        run: echo '${{ secrets.PLAYSTORE_ACCOUNT_KEY }}' > service_account.json

      - name: Upload to playstore
        uses: r0adkll/upload-google-play@v1.0.16
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.onemdev.invmovieconcept1
          releaseFiles: build/app/outputs/bundle/release/*.aab
          track: production
          inAppUpdatePriority: 2
          whatsNewDirectory: distribution/whatsnew
