on:
  push:
    tags:
      - '*'

name: Release Builds
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
          path: 'app'
      - name: Install required build tools for linux
        run: sudo apt-get update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev
      - name: Configure flutter linux configs
        run: |
          flutter config --enable-linux-desktop
          flutter config --no-enable-android
      - name: Trim vector icons
        run: |
          cd app
          flutter pub get
          dart ./scripts/splitVectorIcons.dart
        # flutter clean
      - name: Build linux release
        run: |
          cd app
          flutter build linux --release
      - name: Compress build
        run: |
          cd app/build/linux/x64/release/
          zip -r linux-release.zip bundle

      - name: Create linux Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'app/build/linux/x64/release/linux-release.zip'
          token: ${{ secrets.TOKEN }}
          allowUpdates: true

  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
          path: 'app'
      - run: |
          cd app
          flutter config --enable-web
          flutter config --no-enable-android
          flutter pub get
          dart ./scripts/splitVectorIcons.dart
          flutter build web -t lib/main.web.dart --release
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          PROJECT_PATH: 'app'
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  android-aab:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
      - run: |
          flutter pub get
          dart ./scripts/splitVectorIcons.dart
          flutter build appbundle -t lib/main.mobile.dart
      - name: Create Android Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/bundle/release/app-release.aab'
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
      - name: Create service_account.json
        run: echo '${{ secrets.PLAYSTORE_ACCOUNT_KEY }}' > service_account.json

      - name: Upload to playstore
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.onemdev.invmovieconcept1
          releaseFiles: build/app/outputs/bundle/release/*.aab
          track: production
          inAppUpdatePriority: 2
          whatsNewDirectory: distribution/whatsnew

  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
      - run: |
          flutter pub get
          dart ./scripts/splitVectorIcons.dart
          flutter build apk
          mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/app-release-noads.apk
          flutter build apk -t lib/main.mobile.dart
      - name: Create Android Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.TOKEN }}
          artifacts: 'build/app/outputs/apk/release/app-release.apk,build/app/outputs/apk/release/app-release-noads.apk'

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
          path: 'app'
      - run: |
          cd app
          flutter config --enable-macos-desktop
          flutter config --no-enable-android
          dart scripts/mac.pub.dart
          flutter pub get
          dart ./scripts/splitVectorIcons.dart
          flutter build macos -v --release 
          cd build/macos/Build/Products/Release
          ditto -c -k --sequesterRsrc --keepParent invmovieconcept1.app macos-release.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'app/build/macOS/Build/Products/Release/macos-release.zip'
          token: ${{ secrets.TOKEN }}
          allowUpdates: true

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
          path: 'app'
      - run: |
          cd app
          flutter config --enable-windows-desktop
          flutter config --no-enable-android
          flutter pub get
          dart .\scripts\splitVectorIcons.dart
          flutter build windows --release
          cd build\windows\runner
          Compress-Archive -Path Release -DestinationPath windows-release.zip
      - name: Windows release build for github
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'app\build\windows\runner\windows-release.zip'
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
